default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: 127.0.0.1
  username: root
  password:
  socket: /tmp/mysql.sock
  database: grass_chords_development

test:
  <<: *default
  host: 127.0.0.1
  username: root
  password:
  socket: /tmp/mysql.sock
  database: grass_chords_test

production:
  <<: *default
  host: <%= Rails.application.credentials.db[:grasschords_database_host] %>
  database: grass_chords_production
  username: <%= Rails.application.credentials.db[:grasschords_database_user] %>
  password: <%= Rails.application.credentials.db[:grasschords_database_password] %>
